config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :movies
  resources :theaters
  resources :bookings
  root "movies#index"

  get 'selected', to: 'bookings#selected', as: :selected
  get 'book_ticket', to: 'bookings#book_ticket', as: :book_ticket

  namespace :admin do
    get 'movies_controller/delete'
    post 'movies_controller/update'
    match "movie_update/:movie_id" => "movies_controller#update", via: :patch, as: :admin_movie_update
  	resources :movies_controller
  end

  
end

app/models/available_seat.rb
class AvailableSeat < ActiveRecord::Base
	has_many :seat_availability_times
	has_many :timings, :through => :seat_availability_times 
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	validates :title, :director, :presence => true 
	has_many :movie_theaters
	has_many :theaters, :through => :movie_theaters
end

app/models/movie_theater.rb
class MovieTheater < ActiveRecord::Base
	belongs_to :movie
	belongs_to :theater
end

app/models/seat_availability_time.rb
class SeatAvailabilityTime < ActiveRecord::Base
	belongs_to :available_seat
	belongs_to :timing
end

app/models/theater.rb
class Theater < ActiveRecord::Base
	has_many :movie_theaters
	has_many :movies, :through => :movie_theaters
end

app/models/timing.rb
class Timing < ActiveRecord::Base
	has_many :seat_availability_times
	has_many :available_seats, :through => :seat_availability_times
end

app/controllers/admin/movies_controller_controller.rb
class Admin::MoviesControllerController < ApplicationController

	def new
		@movie = Movie.new 
		@theaters = Theater.all
	end

	def create
		@movie = Movie.new(movie_params)
		if @movie.save
			redirect_to root_path
		else
			render "new"
		end	
	end

	def index
		@theaters = Theater.all
	end

	def show
		@theater = Theater.find(params[:id])
		@movies = @theater.movies
	end

	def edit
		@movie = Movie.find(params[:id])
	end

	def update
		#raise  params.inspect
		@movie = Movie.find(params[:movie_id])
		if @movie.update(movie_params)
			redirect_to admin_movies_controller_path(@movie)
			flash[:notice] = "Updated successfully"
		else
			render edit_admin_movies_controller_path(@movie)	
			flash[:notice] = "Sorry update failed "
		end	
	end

	def delete
		@movies = Movie.all
	end

	def destroy
		@movie = Movie.find(params[:id])
	   # flash[:notice] = @movie
		@movie.destroy
			redirect_to admin_movies_controller_delete_path
	end

	private

		def movie_params
			params.require(:movie).permit(:title, :director)
		end

		def find_movie

		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	before_action :authenticate_customer!
	
	def index
		#raise params.inspect
		#@theater = Theater.find(params[:id]) 
		@timings = Timing.all 
	end

	def show
		@timing = Timing.find(params[:id])
		@available_seats = @timing.available_seats
	end

	def selected
	end

	def book_ticket
		
	end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

	before_action :find_movie,only: [:show, :edit, :update, :destroy]
	before_action :authenticate_customer!, except: [:index, :show]

	def index
		@movies = Movie.all.order("created_at DESC")
	end

	def new
		@movie = Movie.new 
	end

	def create
		@movie = Movie.new(movie_params)
		if @movie.save
			redirect_to root_path
		else
			render "new"
		end	
	end

	def show
		
	end

	def edit
	end

	def update
		raise params.inspect
	end

	def destroy
	end

	private

		def movie_params
			params.require(:movie).permit(:title, :director)
		end

		def find_movie
			@movie = Movie.find(params[:id])
		end
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
	before_action :authenticate_customer!, except: [:index,:show]

	def show
		@movie = Movie.find(params[:id])
		@theaters = @movie.theaters
	end

end

app/helpers/admin/movies_controller_helper.rb
module Admin::MoviesControllerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/admin/movies_controller/_form.html.erb
<div class="container">
	<div class="col-md-6 col-md-offset-3">	
		<%= simple_form_for @movie, url: "/admin/movie_update/#{@movie.id}" do |f| %>
		  <%= f.error_notification %>
			<%= f.input :title, label: "Movie Title",  autofocus: true   %>
			<%= f.input :director%>
			<!-- f.association :theaters, collection: @theaters, input_html: { class: 'multiselectuser' },
				:include_blank => false--> 
			<%= f.button :submit %>
		<% end %>
	</div>	
</div>		

app/views/admin/movies_controller/delete.html.erb
<div class="container">
	<div class="col-md-8 col-md-offset-2">
		<h1 class="text-center title">Movies</h1>
		<% @movies.each do |movie| %>
			<div class="col-md-4">	
				<div class="movies">	
					<div class="col-md-8">	
						<h2 class="movies-title"><%= movie.title %></h2>
					</div>
					<div class="col-md-4">	
						<%= link_to "Delete", admin_movies_controller_path(movie), method: :delete, data: { confirm: "Are you sure want to delete" }, class: "btn btn-custom1" %>
					</div>	
				</div>
			</div>		
		<%end%>
	</div>
</div>		

app/views/admin/movies_controller/edit.html.erb
<div class="container">
	<h1 class="text-center title">Update the Movie</h1>
		<%= render "form" %>
</div>		

app/views/admin/movies_controller/index.html.erb
<div class="container">
	<div class="col-md-8 col-md-offset-2">
		<h1 class="text-center title">Select which Theater you want to update</h1>
		<% @theaters.each do |theater| %>
			<div class="col-md-4">	
				<div class="theaters">	
					<div class="col-md-8">	
						<h2 class="theater-name"><%= theater.name %></h2>
					</div>
					<div class="col-md-4">	
						<%= link_to "Update", admin_movies_controller_path(theater), class: "btn btn-custom1" %>
					</div>	
				</div>
			</div>		
		<%end%>
	</div>
</div>		

app/views/admin/movies_controller/new.html.erb
<div class="container">
		<h1 class="text-center title">New movie</h1>	

		<%= render "form" %>
</div>		

app/views/admin/movies_controller/show.html.erb
<div class="container">
	<div class="col-md-8 col-md-offset-2">
		<h1 class="text-center title">Select which Movie you want to update</h1>
		<% @movies.each do |movie| %>
			<div class="col-md-4">	
				<div class="movies">	
					<div class="col-md-8">	
						<h2 class="movies-title"><%= movie.title %></h2>
					</div>
					<div class="col-md-4">	
						<%= link_to "Edit", edit_admin_movies_controller_path(movie), class: "btn btn-custom1" %>
					</div>	
				</div>
			</div>		
		<%end%>
	</div>
</div>		

app/views/bookings/book_ticket.html.erb
<div class="container">
	<div class="col-md-8 col-md-offset-2">	
		<div class="container">	
			<p><h1>Thank you</h1></p>
			<p><h3>Your tickets are booked....</h3></p>
		</div>	
	</div>
</div>		

app/views/bookings/index.html.erb
<div class="container">
	<div class="col-md-8 col-md-offset-2">
	  <h2 class="time-title"> Timings: </h2>
		<div class="time-row">
		<% @timings.each do |timee| %>
			<div class="col-md-3 ">
				<h3><%= link_to timee.time , booking_path(timee), class: "btn-custom" %></h3>
			</div>
		<% end %>		
	</div>
	</div>			
</div>	

app/views/bookings/show.html.erb
<div class="container">	
	<h2 class="title text-center">Available seats</h2>
	<div class="seats">
	<% @available_seats.each do |available_seat| %>
		<div class="col-md-2">
			<div class="btn-group" data-toggle="buttons">
				<p class="btn btn-success"><input type="checkbox"><%= available_seat.s_no %></p>
			</div>	
		</div>	
	<% end %>
	<p><%= link_to "Book Now", book_ticket_path, class: "btn btn-primary btn-custom btn-book " %></p>
	</div><br/>
	
</div>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookingMovieTickets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar navbar-default">	
		<div class="container">
			<div class="navbar-header">
				<%= link_to "Movie Tickets", root_path, class: "navbar-brand" %>
			</div>	
			<ul class="nav navbar-nav">
				<li><%= link_to "Sign Up", new_customer_registration_path %></li>
				<% if customer_signed_in? %>
					<li><%= link_to "Sign Out", destroy_customer_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Log In", new_customer_session_path %></li>
				<% end %>	
			</ul>	
			<% if customer_signed_in? %>
				<% if current_customer.role == "admin" %>
					<p><%= link_to "Update Movie", admin_movies_controller_index_path, class: "navbar-text navbar-link navbar-right " %></p>
				<% end %>	
			<% end %>
	</div>	
</div>

<p class="notice text-center"><%= notice %></p>
<p class="alert text-center"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/movies/index.html.erb
<div class="container">
		<h1 class="text-center title">Available Movies</h1>

		<% @movies.each do |movie| %>
			<div class="col-md-4">
				<div class="movies">	
					<h2 class="movies-title"><%= movie.title %></h2>
					<%= link_to "Available Theaters", theater_path(movie), class: "btn-custom" %>
				</div>	
			</div>
		<% end %>

</div>	

app/views/theaters/show.html.erb
<div class="container">	
	<h2 class="text-center title">"<u class="movie_name"><%= @movie.title %></u>"  Movie Available Theaters</h2>
	<% @theaters.each do |theater| %>
		<div class="col-md-4">
			<div class="theaters">
				<h2 class="theater-name"><%= theater.name %></h2>
				<%= link_to "Book Ticket", bookings_path, class: "btn-custom" %>
			</div>
		</div>		
	<% end %>
</div>	